#!/usr/bin/env python3

# set server timezone in UTC before time module imported
__import__('os').environ['TZ'] = 'UTC'

import sys
import tpweb
import os

def is_root():
    return os.geteuid() == 0

#only root user can run this script
if not is_root():
    print("You must be root to run this script")
    sys.exit(1)

if __name__ == "__main__":
    tpweb.config.load_config()
    tpweb.cli.main()