version: '3.9'

services:
  ubuntu-server:
    image: ubuntu:latest
    container_name: ubuntu-server
    restart: always  # Automatisch herstarten bij systeemreboot
    ports:
      - "2222:22"  # Poort 2222 op de host wordt gekoppeld aan poort 22 in de container
    environment:
      - DEBIAN_FRONTEND=noninteractive
    command: >
      bash -c "apt update && apt install -y openssh-server && 
               mkdir -p /var/run/sshd && 
               echo 'PermitRootLogin yes' >> /etc/ssh/sshd_config &&
               echo 'PasswordAuthentication yes' >> /etc/ssh/sshd_config &&
               service ssh start && 
               tail -f /dev/null"